###
GET http://localhost:3000/songs

###

GET http://localhost:3000/songs/1

###
POST http://localhost:3000/songs
Content-Type: application/json

{
  "title": "sample_2",
  "album": "sample_2",
  "artist": "sample_2",
  "year": "sample_2"
}

#Need to add dynamic support

###

PATCH http://localhost:3000/songs/4
Content-Type: application/json

{
  "title": "sample_3",
  "album": "sample_3"
}